# Generated by Django 2.1.2 on 2018-10-22 08:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('number_rejected', models.CharField(max_length=10)),
                ('number_accepted', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('F', 'Finished'), ('OH', 'On Hold')], default='NS', max_length=2)),
                ('dispatched_to', models.CharField(max_length=60)),
                ('dispatching_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officer_dispatching_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('number', models.CharField(max_length=10)),
                ('recieved_from', models.CharField(default='', max_length=60)),
                ('contact_number', models.CharField(max_length=16, null=True)),
                ('time_of_completion', models.DateField(blank=True, help_text='Enter a date between now and 4 weeks (default 1).', null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='organization',
            field=models.ForeignKey(blank=True, default='', help_text='What is the name of the Organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Organization', to='entry.Organization'),
        ),
        migrations.AddField(
            model_name='entry',
            name='recieving_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officer_recieving_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Entry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='organization',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='entry.Organization'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
